backend:
  name: git-gateway
  branch: master
media_folder: static/assets
public_folder: assets
collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: src/data/projects
    create: true
    extension: yaml
    fields:
      - name: title
        label: Title
        widget: string
      - name: url
        label: URL
        widget: string
        required: false
      - name: year
        label: Year
        widget: string
      - name: role
        label: Role
        widget: string
  - name: pages
    label: Pages
    label_singular: Page
    files:
      -
        name: about
        label: About
        file: src/data/pages/about.yaml
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "about" }
          - { label: Heading, name: heading, widget: text }
          - { label: Body, name: body, widget: markdown }
      -
        name: contact
        label: Contact
        file: src/data/pages/contact.yaml
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "contact" }
          - { label: Heading, name: heading, widget: text }
          - { label: Body, name: body, widget: markdown }
          -
            label: Form
            name: form
            widget: object
            fields:
              -
                label: Fields
                name: fields
                widget: list
                types:
                  -
                    label: Text
                    name: text
                    widget: object
                    fields:
                      - { label: Placeholder, name: placeholder, widget: string }
                      - { label: Label, name: label, widget: string }
                      - { label: Name, name: name, widget: string }
                  -
                    label: Email
                    name: email
                    widget: object
                    fields:
                    - { label: Placeholder, name: placeholder, widget: string }
                    - { label: Label, name: label, widget: string }
                    - { label: Name, name: name, widget: string }
                  -
                    label: Text Area
                    name: text_area
                    widget: object
                    fields:
                    - { label: Placeholder, name: placeholder, widget: string }
                    - { label: Label, name: label, widget: string }
                    - { label: Name, name: name, widget: string }
                  -
                    label: Radio
                    name: radio
                    widget: object
                    fields:
                      - { label: Label, name: label, widget: string }
                      - { label: Name, name: name, widget: string }
                      -
                        label: Options
                        name: options
                        widget: list
                        fields:
                          - { label: Value, name: value, widget: string }
                          - { label: Label, name: label, widget: string }
              - { label: Submit Button Text, name: submit_text, widget: string  }
